<!-- 模组列表 -->
<template>
  <!--  国内-->
  <table v-if="!isEu">
    <thead>
    <tr class="header" v-if="$lang==='zh-CN'">
      <td>网络制式</td>
      <td>模组型号</td>
      <td>模组OC</td>
      <td>AT指令接入方案</td>
      <td>QuecOpen接入方案</td>
      <td>QuecPython接入方案</td>
    </tr>
    <tr class="header" v-else>
      <td>Network Mode</td>
      <td>Module Type</td>
      <td>Module OC</td>
      <td>AT Command Solution</td>
      <td>QuecOpen Solution</td>
      <td>QuecPython Solution</td>
    </tr>
    </thead>
    <tbody>
    <!-- 5G -->
    <tr>
      <td>5G</td>
      <td>
        RG500U
      </td>
      <td>--</td>
      <td>--</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <!-- 4G Cat.1 -->
    <tr>
      <td rowspan="46">4G Cat.1</td>
      <td rowspan="2">
        EC100N
      </td>
      <td>CN_AB</td>
      <td>--</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_AA</td>
      <td>--</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="4">
        EC200N
      </td>
      <td>CN_AA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_AB</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_GB</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_LA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="6">
        EC200S
      </td>
      <td>CN_AA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_AB</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_LA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_LB</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_MA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_TA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="8">
        EC600N
      </td>
      <td>CN_AA</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_LA</td>
      <td>√</td>
      <td>√</td>
      <td>√</td>
    </tr>
    <tr>
      <td>CN_LC</td>
      <td>√</td>
      <td>√</td>
      <td>√</td>
    </tr>
    <tr>
      <td>CN_LC_BV</td>
      <td>--</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_LC_BT</td>
      <td>--</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_LD</td>
      <td>--</td>
      <td>√</td>
      <td>√</td>
    </tr>
    <tr>
      <td>CN_LE</td>
      <td>√</td>
      <td>√</td>
      <td>√</td>
    </tr>
    <tr>
      <td>CN_LF</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="7">
        EC600S
      </td>
      <td>CN_AA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_AC</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_LA</td>
      <td>√</td>
      <td>√</td>
      <td>√</td>
    </tr>
    <tr>
      <td>CN_LA_HJT</td>
      <td>--</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_LB</td>
      <td>√</td>
      <td>--</td>
      <td>√</td>
    </tr>
    <tr>
      <td>CN_LC</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_LD</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="1">
        EC800N
      </td>
      <td>CN_LA</td>
      <td>√</td>
      <td>√</td>
      <td>√</td>
    </tr>
    <tr>
      <td rowspan="2">
        EG912Y
      </td>
      <td>CN_AA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_AB</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="3">
        EC200A
      </td>
      <td>CN_DA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_HA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_HB</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="6">
        EC200U
      </td>
      <td>CN_AA</td>
      <td>√</td>
      <td>√</td>
      <td>√</td>
    </tr>
    <tr>
      <td>CN_AB</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_LA</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_LB</td>
      <td>√</td>
      <td>√</td>
      <td>√</td>
    </tr>
    <tr>
      <td>CN_MB</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_TA</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="2">
        EC600U
      </td>
      <td>CN_LB</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_LC</td>
      <td>--</td>
      <td>--</td>
      <td>√</td>
    </tr>
    <tr>
      <td rowspan="1">
        EC500U
      </td>
      <td>CN_AB</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="3">
        EC700U
      </td>
      <td>CN_LB</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_MC</td>
      <td>--</td>
      <td>--</td>
      <td>√</td>
    </tr>
    <tr>
      <td>CN_SC</td>
      <td>--</td>
      <td>--</td>
      <td>√</td>
    </tr>
    <tr>
      <td rowspan="1">
        EG915U
      </td>
      <td>CN_AB</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <!-- 4G Cat.4 -->
    <tr>
      <td rowspan="14">4G Cat.4</td>
      <td rowspan="3">
        EC200A
      </td>
      <td>CN_DA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_HA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>CN_HB</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="7">
        EG915U
      </td>
      <td>FALG</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>FDLG</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>FHLG</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>FILG</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>HCLG</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>HCLG_AUD</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>HDLG</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="1">
        EG915U
      </td>
      <td>--</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="3">
        EG915U
      </td>
      <td>--</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>GC</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>GD</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <!-- CATM -->
    <tr>
      <td>CATM</td>
      <td>
        BG96
      </td>
      <td>MA</td>
      <td>--</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <!-- NB-IOT -->
    <tr>
      <td rowspan="2">NB-IOT</td>
      <td>
        BC25
      </td>
      <td>PA</td>
      <td>√</td>
      <td>√</td>
      <td>√</td>
    </tr>
    <tr>
      <td>
        BC260Y
      </td>
      <td>--</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <!-- WIFI-BLE -->
    <tr>
      <td rowspan="8">WIFI-BLE</td>
      <td rowspan="7">
        FC41D
      </td>
      <td>ABMD</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>ACMD</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>ADMD</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AEMD</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AFMD</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AATB</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AGTB</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>
        ESP32
      </td>
      <td>--</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    </tbody>
  </table>

  <!--  海外-->
  <table v-else>
    <thead>
    <tr class="header" v-if="$lang==='zh-CN'">
      <td>网络制式</td>
      <td>模组型号</td>
      <td>模组OC</td>
      <td>AT指令接入方案</td>
      <td>QuecOpen接入方案</td>
      <td>QuecPython接入方案</td>
    </tr>
    <tr class="header" v-else>
      <td>Network Mode</td>
      <td>Module Type</td>
      <td>Module OC</td>
      <td>AT Command Solution</td>
      <td>QuecOpen Solution</td>
      <td>QuecPython Solution</td>
    </tr>
    </thead>
    <tbody>
    <!-- 5G -->
    <tr>
      <td>5G</td>
      <td>
        RG500U
      </td>
      <td>--</td>
      <td>--</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <!-- 4G Cat.1 -->
    <tr>
      <td rowspan="17">4G Cat.1</td>
      <td rowspan="3">
        EC200S
      </td>
      <td>AU_AA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>EN_AA</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>EU_AA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="3">
        EG912Y
      </td>
      <td>EU_AA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>EU_AC</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>EU_AD</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="2">
        EG915N
      </td>
      <td>EU_AG</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>EU_AC</td>
      <td>--</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="5">
        EC200U
      </td>
      <td>AU_AA</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AU_AB</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>EU_AA</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>EU_AB</td>
      <td>√</td>
      <td>√</td>
      <td>√</td>
    </tr>
    <tr>
      <td>EU_AT</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>
        EC600U
      </td>
      <td>EU_AB</td>
      <td>√</td>
      <td>√</td>
      <td>√</td>
    </tr>
    <tr>
      <td>
        EG700U
      </td>
      <td>LA_AB</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="2">
        EG915U
      </td>
      <td>EN_AB</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>LA_AB</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <!-- 4G Cat.4 -->
    <tr>
      <td rowspan="41">4G Cat.4</td>
      <td rowspan="3">
        EC200A
      </td>
      <td>AU_HA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>EH_AA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>EU_AA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="8">
        EC21
      </td>
      <td>ADL</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AUGC</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AUXGA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AUX-GAA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>ECGA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>EUGA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>EUXGA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>JFA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="16">
        EC25
      </td>
      <td>ADL</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AF</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AFDL</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AFFD</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AFX</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AFXD</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AUFA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AUFA-GA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AUTFA-GA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AUXGA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>ECGA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>EFA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>EFA_KR</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>EUXGA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>JFA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>JLFA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>
        EG21G
      </td>
      <td></td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="3">
        EG25G
      </td>
      <td></td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>GC</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>GD</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="7">
        EG91
      </td>
      <td>EFB</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>EXGA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>NA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>NAX</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>NAXD</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>NAXDL</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>NS</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td rowspan="2">
        EG95
      </td>
      <td>EXGA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>NAX</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <tr>
      <td>
        EM05
      </td>
      <td>EFA</td>
      <td>√</td>
      <td>--</td>
      <td>--</td>
    </tr>
    <!-- CATM -->
    <tr>
      <td rowspan="3">CATM</td>
      <td>
        BG96
      </td>
      <td>MA</td>
      <td>--</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>
        BG95
      </td>
      <td>M3</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>
        BG600L
      </td>
      <td></td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <!-- WIFI-BLE -->
    <tr>
      <td rowspan="8">WIFI-BLE</td>
      <td rowspan="7">
        FC41D
      </td>
      <td>ABMD</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>ACMD</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>ADMD</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AEMD</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AFMD</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AATB</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>AGTB</td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    <tr>
      <td>
        ESP32
      </td>
      <td></td>
      <td>√</td>
      <td>√</td>
      <td>--</td>
    </tr>
    </tbody>
  </table>
</template>

<script>
export default {
  mounted() {
    console.log(this.isEu)
    console.log(this.$lang);
  }
}
</script>

<style lang="stylus" scoped>
table {
  thead {
    width: 100%;

    .header {
      width: 100%;
      background-color: #fafafc;
      font-weight: 700;
      color: blck;

      td {
        font-weight: 700;
        color: black;
      }
    }
  }
}
</style>
